config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do

  mount Sidekiq::Web, at: '/sidekiq'

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV.fetch('SIDEKIQ_USERNAME', ''))) &
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV.fetch('SIDEKIQ_PASSWORD', '')))
  end # if Rails.env.production?

  root to: 'home#index'

  resources :email_templates

  post 'fetch_results', to: 'results#fetch'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/email_template.rb
# frozen_string_literal: true

class EmailTemplate < ApplicationRecord
  EMAIL_TYPES = %w[twitter linkedin]

  has_many :results, dependent: :nullify
  belongs_to :user

  validates :template_name, presence: true, uniqueness: true
  validates :user, presence: true
  validates :email_type, inclusion: { in: EMAIL_TYPES, message: 'Email type not supported' }
end

app/models/result.rb
# frozen_string_literal: true

class Result < ApplicationRecord
  enum status: [:created, :downloaded, :sent, :failed]

  belongs_to :user
  belongs_to :email_template

  validates :user, :email_template, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

  has_many :email_templates, dependent: :delete_all # do not validate anything, just delete
  has_many :results, dependent: :delete_all

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :email, format: { with: EMAIL_REGEX }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :current_user

  def current_user
    @current_user ||= User.first
  end
end

app/controllers/email_templates_controller.rb
# frozen_string_literal: true

class EmailTemplatesController < ApplicationController
  before_action :find_email_template, only: [:show, :edit, :update, :destroy]

  def index
    @email_templates = EmailTemplate.all
  end

  def show
  end

  def new
    @email_template = EmailTemplate.new
  end

  def edit
  end

  def create
    @email_template = EmailTemplate.new(email_template_params.merge(user_id: @current_user.id))

    if @email_template.save
      redirect_to email_templates_path, notice: 'Email template was successfully created.'
    else
      render :new
    end
  end

  def update
    if @email_template.update(email_template_params)
      redirect_to email_templates_path, notice: 'Email template was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @email_template.destroy!
    redirect_to email_templates_path, notice: 'Email template was successfully deleted.'
  end

  private

  def find_email_template
    @email_template = EmailTemplate.find(params[:id])
  end

  def email_template_params
    params.fetch(:email_template, {}).permit(:template_name, :sender_name, :subject, :description, :body)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
  end
end

app/controllers/results_controller.rb
# frozen_string_literal: true

class ResultsController < ApplicationController
  def fetch
    check_params
    ResultsService.new(current_user, params, TwitterService.client).call
  rescue StandardError => e
    @error = e
  ensure
    respond_to { |format| format.js }
  end

  private

  def check_params
    raise 'Receiver Email param is missing' unless params.dig(:input, :receiver_email).present?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/email_templates/_form.html.erb
<%= form_with(model: email_template, local: true) do |form| %>
  <div class="form-group">
    <% if email_template.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(email_template.errors.count, "error") %> prohibited this email_template from being saved:</h2>
        <ul>
          <% email_template.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
  <br/>
  <div class="form-group col-6">
    <label for="template_name">Template Name</label>
    <%= form.text_field(:template_name, class: 'form-control', id: 'template_name', required: true) %>
  </div>
  <div class="form-group col-6">
    <label for="sender_name">Sender</label>
    <%= form.text_field(:sender_name, class: 'form-control', id: 'sender_name') %>
  </div>
  <div class="form-group col-6">
    <label for="subject">Subject</label>
    <%= form.text_field(:subject, class: 'form-control', id: 'subject') %>
  </div>
  <div class="form-group col-6">
    <label for="description">Description</label>
    <%= form.text_field(:description, class: 'form-control', id: 'description') %>
  </div>
  <div class="form-group col-6">
    <%= form.text_area :body, class: "tinymce form-control", rows: 10, cols: 120, id: 'body' %>
    <%= tinymce %>
  </div>
  <br/>
  <div class="form-group col-6">
    <div class="actions">
      <%= form.submit(class: 'btn btn-primary') %>
    </div>
  </div>
<% end %>

app/views/email_templates/edit.html.erb
<h3 class="title">Editing Email Template</h3>
<br/>
<%= render 'form', email_template: @email_template %>
<br/>
<%= link_to 'Show', email_template_path(@email_template) %> | <%= link_to 'Back', email_templates_path %>

app/views/email_templates/index.html.erb
<div class=col-12>
  <h3 class="title">Email templates</h3>
  <br/>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Template name</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @email_templates.each do |email_template| %>
        <tr>
          <td scope="col"><%= email_template.template_name %></td>
          <td scope="col">
            <%= link_to 'Show', email_template_path(email_template) %> |
            <%= link_to 'Edit', edit_email_template_path(email_template) %> |
            <%= link_to 'Destroy', email_template_path(email_template), method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <%= link_to 'New Email Template', new_email_template_path %>
</div>

app/views/email_templates/new.html.erb
<h3 class="title">New Email Template</h3>
<br/>
<%= render 'form', email_template: @email_template %>
<br/>
<%= link_to 'Back', email_templates_path %>

app/views/email_templates/show.html.erb
<div class=col-12>
  <h3 class="title">Email template details</h3>
  <br/>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Template name</th>
        <th scope="col">Sender</th>
        <th scope="col">Subject</th>
        <th scope="col">Description</th>
        <th scope="col">User</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td scope="col"><%= @email_template.template_name %></td>
        <td scope="col"><%= @email_template.sender_name %></td>
        <td scope="col"><%= @email_template.subject %></td>
        <td scope="col"><%= @email_template.description %></td>
        <td scope="col"><%= @email_template.user.name %></td>
        <td scope="col"><%= link_to 'Edit', edit_email_template_path(@email_template) %> | <%= link_to 'Back', email_templates_path %></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/home/index.html.erb
<div class=col-12>
  <h3 class="title">Fetch tweets</h3>
  <br/>
  <%= form_tag(fetch_results_url, method: :post, remote: true) do %>
    <div class="form-group col-6">
      <label for="email_template_id">Select email template</label>
      <%= select_tag('input[email_template_id]', options_for_select(EmailTemplate.all.pluck(:template_name, :id), class: 'form-control', id: 'email_template_id')) %>
    </div>
    <div class="form-group col-4">
      <label for="receiver_email">Receiver Email</label>
      <%= text_field_tag('input[receiver_email]', '', class: 'form-control', id: 'receiver_email', type: 'email', required: true) %>
    </div>
    <div class="form-group col-6">
      <label for="period_from">Period From</label>
      <%= datetime_field_tag('input[period_from]', class: 'form-control', id: 'period_from') %>
    </div>
    <div class="form-group col-6">
      <label for="period_to">Period To</label>
      <%= datetime_field_tag('input[period_to]', class: 'form-control', id: 'period_to') %>
    </div>
    <br/>
    <div class="form-group col-6">
      <div class="actions">
        <%= submit_tag('Fetch', class: 'btn btn-primary', data: { disable_with: 'Processing...' }) %>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AService</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= tinymce_assets %>
    <script type="text/javascript" src="/assets/tinymce.js"></script>
  </head>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-12">
          <div class="configurations">
            <%= link_to('Home', root_path) %> |
            <%= link_to('Email Templates', email_templates_path) %>
            <hr>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-12">
          <div class="flash-messages">
            <% flash.each do |type, msg| %>
              <div>
                <p><%= msg %></p>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/results/fetch.js.erb
<% if @error %>
  alert('Something went wrong: <%= @error.message %>');
<% else %>
  alert('Fetching of results has been initiated...');
<% end %>